version: "3.9"

services:
  server:
    container_name: gminlee-IS24-server
    restart: unless-stopped
    image: is24-server-test:1.0.0
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
  client:
    container_name: gminlee-IS24-client
    restart: unless-stopped
    image: is24-client-test:1.0.0
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    command: sh -c "npm rebuild esbuild && npm run dev"
    depends_on:
      - server
